// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyId {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListStrategiesRequest {
    #[prost(enumeration = "StrategyState", tag = "1")]
    pub state_filter: i32,
    #[prost(enumeration = "TradingMode", tag = "2")]
    pub mode_filter: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Strategy {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub file_path: ::prost::alloc::string::String,
    #[prost(enumeration = "StrategyState", tag = "5")]
    pub state: i32,
    #[prost(enumeration = "TradingMode", tag = "6")]
    pub mode: i32,
    #[prost(map = "string, string", tag = "7")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "8")]
    pub metrics: ::core::option::Option<StrategyMetrics>,
    #[prost(int64, tag = "9")]
    pub created_at: i64,
    #[prost(int64, tag = "10")]
    pub last_run_at: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StrategyMetrics {
    #[prost(double, tag = "1")]
    pub total_pnl: f64,
    #[prost(int32, tag = "2")]
    pub total_trades: i32,
    #[prost(int32, tag = "3")]
    pub winning_trades: i32,
    #[prost(double, tag = "4")]
    pub win_rate: f64,
    #[prost(double, tag = "5")]
    pub max_drawdown: f64,
    #[prost(double, tag = "6")]
    pub sharpe_ratio: f64,
    #[prost(double, tag = "7")]
    pub profit_factor: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyList {
    #[prost(message, repeated, tag = "1")]
    pub strategies: ::prost::alloc::vec::Vec<Strategy>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartStrategyRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "TradingMode", tag = "2")]
    pub mode: i32,
    #[prost(map = "string, string", tag = "3")]
    pub runtime_params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyStatus {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "StrategyState", tag = "2")]
    pub state: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StrategyConfig {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "3")]
    pub risk_limits: ::core::option::Option<RiskLimits>,
    #[prost(string, repeated, tag = "4")]
    pub instruments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RiskLimits {
    #[prost(double, tag = "1")]
    pub max_position_value: f64,
    #[prost(double, tag = "2")]
    pub max_daily_loss: f64,
    #[prost(double, tag = "3")]
    pub max_drawdown: f64,
    #[prost(int32, tag = "4")]
    pub max_open_orders: i32,
    #[prost(int32, tag = "5")]
    pub max_trades_per_day: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Signal {
    #[prost(string, tag = "1")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(enumeration = "SignalType", tag = "3")]
    pub signal_type: i32,
    #[prost(enumeration = "SignalSide", tag = "4")]
    pub side: i32,
    #[prost(double, tag = "5")]
    pub price: f64,
    #[prost(int32, tag = "6")]
    pub quantity: i32,
    #[prost(string, tag = "7")]
    pub reason: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    #[prost(string, tag = "1")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(enumeration = "LogLevel", tag = "2")]
    pub level: i32,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub timestamp: i64,
    #[prost(map = "string, string", tag = "5")]
    pub context: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BacktestRequest {
    #[prost(string, tag = "1")]
    pub strategy_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub start_date: i64,
    #[prost(int64, tag = "3")]
    pub end_date: i64,
    #[prost(double, tag = "4")]
    pub initial_capital: f64,
    #[prost(map = "string, string", tag = "5")]
    pub parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BacktestUpdate {
    #[prost(enumeration = "BacktestPhase", tag = "1")]
    pub phase: i32,
    /// 0.0 to 1.0
    #[prost(double, tag = "2")]
    pub progress: f64,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    /// Populated when phase is COMPLETE
    #[prost(message, optional, tag = "4")]
    pub result: ::core::option::Option<BacktestResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BacktestResult {
    #[prost(double, tag = "1")]
    pub total_return: f64,
    #[prost(double, tag = "2")]
    pub total_pnl: f64,
    #[prost(int32, tag = "3")]
    pub total_trades: i32,
    #[prost(double, tag = "4")]
    pub win_rate: f64,
    #[prost(double, tag = "5")]
    pub max_drawdown: f64,
    #[prost(double, tag = "6")]
    pub sharpe_ratio: f64,
    #[prost(double, tag = "7")]
    pub sortino_ratio: f64,
    #[prost(double, tag = "8")]
    pub profit_factor: f64,
    #[prost(double, tag = "9")]
    pub avg_trade_pnl: f64,
    #[prost(double, tag = "10")]
    pub max_consecutive_wins: f64,
    #[prost(double, tag = "11")]
    pub max_consecutive_losses: f64,
    #[prost(message, repeated, tag = "12")]
    pub equity_curve: ::prost::alloc::vec::Vec<EquityPoint>,
    #[prost(message, repeated, tag = "13")]
    pub trades: ::prost::alloc::vec::Vec<TradeRecord>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EquityPoint {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(double, tag = "2")]
    pub equity: f64,
    #[prost(double, tag = "3")]
    pub drawdown: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TradeRecord {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(enumeration = "SignalSide", tag = "2")]
    pub side: i32,
    #[prost(int64, tag = "3")]
    pub entry_time: i64,
    #[prost(int64, tag = "4")]
    pub exit_time: i64,
    #[prost(double, tag = "5")]
    pub entry_price: f64,
    #[prost(double, tag = "6")]
    pub exit_price: f64,
    #[prost(int32, tag = "7")]
    pub quantity: i32,
    #[prost(double, tag = "8")]
    pub pnl: f64,
    #[prost(double, tag = "9")]
    pub pnl_percent: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StrategyState {
    Idle = 0,
    Running = 1,
    Paused = 2,
    Stopped = 3,
    Error = 4,
}
impl StrategyState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Idle => "STRATEGY_STATE_IDLE",
            Self::Running => "STRATEGY_STATE_RUNNING",
            Self::Paused => "STRATEGY_STATE_PAUSED",
            Self::Stopped => "STRATEGY_STATE_STOPPED",
            Self::Error => "STRATEGY_STATE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STRATEGY_STATE_IDLE" => Some(Self::Idle),
            "STRATEGY_STATE_RUNNING" => Some(Self::Running),
            "STRATEGY_STATE_PAUSED" => Some(Self::Paused),
            "STRATEGY_STATE_STOPPED" => Some(Self::Stopped),
            "STRATEGY_STATE_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TradingMode {
    Backtest = 0,
    Paper = 1,
    Live = 2,
}
impl TradingMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Backtest => "TRADING_MODE_BACKTEST",
            Self::Paper => "TRADING_MODE_PAPER",
            Self::Live => "TRADING_MODE_LIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRADING_MODE_BACKTEST" => Some(Self::Backtest),
            "TRADING_MODE_PAPER" => Some(Self::Paper),
            "TRADING_MODE_LIVE" => Some(Self::Live),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SignalType {
    Entry = 0,
    Exit = 1,
    ScaleIn = 2,
    ScaleOut = 3,
}
impl SignalType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Entry => "SIGNAL_TYPE_ENTRY",
            Self::Exit => "SIGNAL_TYPE_EXIT",
            Self::ScaleIn => "SIGNAL_TYPE_SCALE_IN",
            Self::ScaleOut => "SIGNAL_TYPE_SCALE_OUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIGNAL_TYPE_ENTRY" => Some(Self::Entry),
            "SIGNAL_TYPE_EXIT" => Some(Self::Exit),
            "SIGNAL_TYPE_SCALE_IN" => Some(Self::ScaleIn),
            "SIGNAL_TYPE_SCALE_OUT" => Some(Self::ScaleOut),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SignalSide {
    Long = 0,
    Short = 1,
}
impl SignalSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Long => "SIGNAL_SIDE_LONG",
            Self::Short => "SIGNAL_SIDE_SHORT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIGNAL_SIDE_LONG" => Some(Self::Long),
            "SIGNAL_SIDE_SHORT" => Some(Self::Short),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogLevel {
    Debug = 0,
    Info = 1,
    Warning = 2,
    Error = 3,
}
impl LogLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Debug => "LOG_LEVEL_DEBUG",
            Self::Info => "LOG_LEVEL_INFO",
            Self::Warning => "LOG_LEVEL_WARNING",
            Self::Error => "LOG_LEVEL_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_LEVEL_DEBUG" => Some(Self::Debug),
            "LOG_LEVEL_INFO" => Some(Self::Info),
            "LOG_LEVEL_WARNING" => Some(Self::Warning),
            "LOG_LEVEL_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BacktestPhase {
    Loading = 0,
    Running = 1,
    Complete = 2,
    Error = 3,
}
impl BacktestPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Loading => "BACKTEST_PHASE_LOADING",
            Self::Running => "BACKTEST_PHASE_RUNNING",
            Self::Complete => "BACKTEST_PHASE_COMPLETE",
            Self::Error => "BACKTEST_PHASE_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BACKTEST_PHASE_LOADING" => Some(Self::Loading),
            "BACKTEST_PHASE_RUNNING" => Some(Self::Running),
            "BACKTEST_PHASE_COMPLETE" => Some(Self::Complete),
            "BACKTEST_PHASE_ERROR" => Some(Self::Error),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod strategy_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Strategy management service for algorithmic trading
    #[derive(Debug, Clone)]
    pub struct StrategyServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StrategyServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StrategyServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StrategyServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StrategyServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// List all strategies
        pub async fn list_strategies(
            &mut self,
            request: impl tonic::IntoRequest<super::ListStrategiesRequest>,
        ) -> std::result::Result<tonic::Response<super::StrategyList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/ListStrategies",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "ListStrategies",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get strategy details
        pub async fn get_strategy(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::Strategy>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/GetStrategy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "GetStrategy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Start a strategy
        pub async fn start_strategy(
            &mut self,
            request: impl tonic::IntoRequest<super::StartStrategyRequest>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/StartStrategy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "StartStrategy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stop a strategy
        pub async fn stop_strategy(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/StopStrategy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "StopStrategy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Pause a strategy
        pub async fn pause_strategy(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/PauseStrategy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "PauseStrategy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream strategy signals
        pub async fn get_strategy_signals(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyId>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Signal>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/GetStrategySignals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "GetStrategySignals",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream strategy logs
        pub async fn get_strategy_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyId>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/GetStrategyLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "GetStrategyLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Run backtest
        pub async fn run_backtest(
            &mut self,
            request: impl tonic::IntoRequest<super::BacktestRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BacktestUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/RunBacktest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "RunBacktest",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Configure strategy parameters
        pub async fn configure_strategy(
            &mut self,
            request: impl tonic::IntoRequest<super::StrategyConfig>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.strategy.StrategyService/ConfigureStrategy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.strategy.StrategyService",
                        "ConfigureStrategy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod strategy_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StrategyServiceServer.
    #[async_trait]
    pub trait StrategyService: std::marker::Send + std::marker::Sync + 'static {
        /// List all strategies
        async fn list_strategies(
            &self,
            request: tonic::Request<super::ListStrategiesRequest>,
        ) -> std::result::Result<tonic::Response<super::StrategyList>, tonic::Status>;
        /// Get strategy details
        async fn get_strategy(
            &self,
            request: tonic::Request<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::Strategy>, tonic::Status>;
        /// Start a strategy
        async fn start_strategy(
            &self,
            request: tonic::Request<super::StartStrategyRequest>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status>;
        /// Stop a strategy
        async fn stop_strategy(
            &self,
            request: tonic::Request<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status>;
        /// Pause a strategy
        async fn pause_strategy(
            &self,
            request: tonic::Request<super::StrategyId>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status>;
        /// Server streaming response type for the GetStrategySignals method.
        type GetStrategySignalsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Signal, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream strategy signals
        async fn get_strategy_signals(
            &self,
            request: tonic::Request<super::StrategyId>,
        ) -> std::result::Result<
            tonic::Response<Self::GetStrategySignalsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the GetStrategyLogs method.
        type GetStrategyLogsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::LogEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream strategy logs
        async fn get_strategy_logs(
            &self,
            request: tonic::Request<super::StrategyId>,
        ) -> std::result::Result<
            tonic::Response<Self::GetStrategyLogsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the RunBacktest method.
        type RunBacktestStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BacktestUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Run backtest
        async fn run_backtest(
            &self,
            request: tonic::Request<super::BacktestRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::RunBacktestStream>,
            tonic::Status,
        >;
        /// Configure strategy parameters
        async fn configure_strategy(
            &self,
            request: tonic::Request<super::StrategyConfig>,
        ) -> std::result::Result<tonic::Response<super::StrategyStatus>, tonic::Status>;
    }
    /// Strategy management service for algorithmic trading
    #[derive(Debug)]
    pub struct StrategyServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StrategyServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StrategyServiceServer<T>
    where
        T: StrategyService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nautilus.gateway.strategy.StrategyService/ListStrategies" => {
                    #[allow(non_camel_case_types)]
                    struct ListStrategiesSvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::ListStrategiesRequest>
                    for ListStrategiesSvc<T> {
                        type Response = super::StrategyList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListStrategiesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::list_strategies(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListStrategiesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/GetStrategy" => {
                    #[allow(non_camel_case_types)]
                    struct GetStrategySvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::StrategyId>
                    for GetStrategySvc<T> {
                        type Response = super::Strategy;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::get_strategy(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStrategySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/StartStrategy" => {
                    #[allow(non_camel_case_types)]
                    struct StartStrategySvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::StartStrategyRequest>
                    for StartStrategySvc<T> {
                        type Response = super::StrategyStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StartStrategyRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::start_strategy(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartStrategySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/StopStrategy" => {
                    #[allow(non_camel_case_types)]
                    struct StopStrategySvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::StrategyId>
                    for StopStrategySvc<T> {
                        type Response = super::StrategyStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::stop_strategy(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StopStrategySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/PauseStrategy" => {
                    #[allow(non_camel_case_types)]
                    struct PauseStrategySvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::StrategyId>
                    for PauseStrategySvc<T> {
                        type Response = super::StrategyStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::pause_strategy(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PauseStrategySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/GetStrategySignals" => {
                    #[allow(non_camel_case_types)]
                    struct GetStrategySignalsSvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::ServerStreamingService<super::StrategyId>
                    for GetStrategySignalsSvc<T> {
                        type Response = super::Signal;
                        type ResponseStream = T::GetStrategySignalsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::get_strategy_signals(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStrategySignalsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/GetStrategyLogs" => {
                    #[allow(non_camel_case_types)]
                    struct GetStrategyLogsSvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::ServerStreamingService<super::StrategyId>
                    for GetStrategyLogsSvc<T> {
                        type Response = super::LogEntry;
                        type ResponseStream = T::GetStrategyLogsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyId>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::get_strategy_logs(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStrategyLogsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/RunBacktest" => {
                    #[allow(non_camel_case_types)]
                    struct RunBacktestSvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::ServerStreamingService<super::BacktestRequest>
                    for RunBacktestSvc<T> {
                        type Response = super::BacktestUpdate;
                        type ResponseStream = T::RunBacktestStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BacktestRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::run_backtest(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RunBacktestSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.strategy.StrategyService/ConfigureStrategy" => {
                    #[allow(non_camel_case_types)]
                    struct ConfigureStrategySvc<T: StrategyService>(pub Arc<T>);
                    impl<
                        T: StrategyService,
                    > tonic::server::UnaryService<super::StrategyConfig>
                    for ConfigureStrategySvc<T> {
                        type Response = super::StrategyStatus;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StrategyConfig>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StrategyService>::configure_strategy(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ConfigureStrategySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StrategyServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nautilus.gateway.strategy.StrategyService";
    impl<T> tonic::server::NamedService for StrategyServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
