// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionRequest {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    /// Optional filter: MIS, CNC, NRML
    #[prost(string, tag = "2")]
    pub product_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionUpdate {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub product: ::prost::alloc::string::String,
    /// Net quantity (positive = long, negative = short)
    #[prost(int32, tag = "4")]
    pub quantity: i32,
    #[prost(double, tag = "5")]
    pub average_price: f64,
    #[prost(double, tag = "6")]
    pub ltp: f64,
    #[prost(double, tag = "7")]
    pub pnl: f64,
    #[prost(double, tag = "8")]
    pub pnl_percent: f64,
    #[prost(double, tag = "9")]
    pub value: f64,
    #[prost(double, tag = "10")]
    pub buy_quantity: f64,
    #[prost(double, tag = "11")]
    pub sell_quantity: f64,
    #[prost(double, tag = "12")]
    pub buy_value: f64,
    #[prost(double, tag = "13")]
    pub sell_value: f64,
    #[prost(int64, tag = "14")]
    pub timestamp: i64,
    #[prost(string, tag = "15")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HoldingsRequest {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Holding {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub isin: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub quantity: i32,
    /// T+1 pending quantity
    #[prost(int32, tag = "5")]
    pub t1_quantity: i32,
    #[prost(double, tag = "6")]
    pub average_price: f64,
    #[prost(double, tag = "7")]
    pub ltp: f64,
    #[prost(double, tag = "8")]
    pub pnl: f64,
    #[prost(double, tag = "9")]
    pub pnl_percent: f64,
    #[prost(double, tag = "10")]
    pub invested_value: f64,
    #[prost(double, tag = "11")]
    pub current_value: f64,
    #[prost(string, tag = "12")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HoldingsList {
    #[prost(message, repeated, tag = "1")]
    pub holdings: ::prost::alloc::vec::Vec<Holding>,
    #[prost(double, tag = "2")]
    pub total_invested: f64,
    #[prost(double, tag = "3")]
    pub total_current: f64,
    #[prost(double, tag = "4")]
    pub total_pnl: f64,
    #[prost(double, tag = "5")]
    pub total_pnl_percent: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginRequest {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarginUpdate {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    /// equity, commodity
    #[prost(string, tag = "2")]
    pub segment: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub available: f64,
    #[prost(double, tag = "4")]
    pub used: f64,
    #[prost(double, tag = "5")]
    pub total: f64,
    #[prost(double, tag = "6")]
    pub cash: f64,
    #[prost(double, tag = "7")]
    pub collateral: f64,
    #[prost(int64, tag = "8")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PnLRequest {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(enumeration = "PnLScope", tag = "2")]
    pub scope: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PnLUpdate {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub realized_pnl: f64,
    #[prost(double, tag = "3")]
    pub unrealized_pnl: f64,
    #[prost(double, tag = "4")]
    pub total_pnl: f64,
    /// Brokerage, taxes, etc.
    #[prost(double, tag = "5")]
    pub total_charges: f64,
    #[prost(int64, tag = "6")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DaySummaryRequest {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DaySummary {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub total_trades: i32,
    #[prost(int32, tag = "3")]
    pub winning_trades: i32,
    #[prost(int32, tag = "4")]
    pub losing_trades: i32,
    #[prost(double, tag = "5")]
    pub gross_pnl: f64,
    #[prost(double, tag = "6")]
    pub charges: f64,
    #[prost(double, tag = "7")]
    pub net_pnl: f64,
    #[prost(double, tag = "8")]
    pub turnover: f64,
    #[prost(double, tag = "9")]
    pub max_profit_trade: f64,
    #[prost(double, tag = "10")]
    pub max_loss_trade: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PnLScope {
    PnlScopeDay = 0,
    PnlScopeWeek = 1,
    PnlScopeMonth = 2,
    PnlScopeAll = 3,
}
impl PnLScope {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PnlScopeDay => "PNL_SCOPE_DAY",
            Self::PnlScopeWeek => "PNL_SCOPE_WEEK",
            Self::PnlScopeMonth => "PNL_SCOPE_MONTH",
            Self::PnlScopeAll => "PNL_SCOPE_ALL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PNL_SCOPE_DAY" => Some(Self::PnlScopeDay),
            "PNL_SCOPE_WEEK" => Some(Self::PnlScopeWeek),
            "PNL_SCOPE_MONTH" => Some(Self::PnlScopeMonth),
            "PNL_SCOPE_ALL" => Some(Self::PnlScopeAll),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod portfolio_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Portfolio management service for positions, holdings, and margins
    #[derive(Debug, Clone)]
    pub struct PortfolioServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PortfolioServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PortfolioServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PortfolioServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PortfolioServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stream position updates
        pub async fn get_positions(
            &mut self,
            request: impl tonic::IntoRequest<super::PositionRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PositionUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.portfolio.PortfolioService/GetPositions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.portfolio.PortfolioService",
                        "GetPositions",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get holdings (delivery shares)
        pub async fn get_holdings(
            &mut self,
            request: impl tonic::IntoRequest<super::HoldingsRequest>,
        ) -> std::result::Result<tonic::Response<super::HoldingsList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.portfolio.PortfolioService/GetHoldings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.portfolio.PortfolioService",
                        "GetHoldings",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream margin updates
        pub async fn get_margins(
            &mut self,
            request: impl tonic::IntoRequest<super::MarginRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MarginUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.portfolio.PortfolioService/GetMargins",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.portfolio.PortfolioService",
                        "GetMargins",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Stream P&L updates
        pub async fn get_pn_l(
            &mut self,
            request: impl tonic::IntoRequest<super::PnLRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PnLUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.portfolio.PortfolioService/GetPnL",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.portfolio.PortfolioService",
                        "GetPnL",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get day's activity summary
        pub async fn get_day_summary(
            &mut self,
            request: impl tonic::IntoRequest<super::DaySummaryRequest>,
        ) -> std::result::Result<tonic::Response<super::DaySummary>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.portfolio.PortfolioService/GetDaySummary",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.portfolio.PortfolioService",
                        "GetDaySummary",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod portfolio_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PortfolioServiceServer.
    #[async_trait]
    pub trait PortfolioService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the GetPositions method.
        type GetPositionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PositionUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream position updates
        async fn get_positions(
            &self,
            request: tonic::Request<super::PositionRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::GetPositionsStream>,
            tonic::Status,
        >;
        /// Get holdings (delivery shares)
        async fn get_holdings(
            &self,
            request: tonic::Request<super::HoldingsRequest>,
        ) -> std::result::Result<tonic::Response<super::HoldingsList>, tonic::Status>;
        /// Server streaming response type for the GetMargins method.
        type GetMarginsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::MarginUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream margin updates
        async fn get_margins(
            &self,
            request: tonic::Request<super::MarginRequest>,
        ) -> std::result::Result<tonic::Response<Self::GetMarginsStream>, tonic::Status>;
        /// Server streaming response type for the GetPnL method.
        type GetPnLStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::PnLUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream P&L updates
        async fn get_pn_l(
            &self,
            request: tonic::Request<super::PnLRequest>,
        ) -> std::result::Result<tonic::Response<Self::GetPnLStream>, tonic::Status>;
        /// Get day's activity summary
        async fn get_day_summary(
            &self,
            request: tonic::Request<super::DaySummaryRequest>,
        ) -> std::result::Result<tonic::Response<super::DaySummary>, tonic::Status>;
    }
    /// Portfolio management service for positions, holdings, and margins
    #[derive(Debug)]
    pub struct PortfolioServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PortfolioServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PortfolioServiceServer<T>
    where
        T: PortfolioService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nautilus.gateway.portfolio.PortfolioService/GetPositions" => {
                    #[allow(non_camel_case_types)]
                    struct GetPositionsSvc<T: PortfolioService>(pub Arc<T>);
                    impl<
                        T: PortfolioService,
                    > tonic::server::ServerStreamingService<super::PositionRequest>
                    for GetPositionsSvc<T> {
                        type Response = super::PositionUpdate;
                        type ResponseStream = T::GetPositionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PositionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PortfolioService>::get_positions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPositionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.portfolio.PortfolioService/GetHoldings" => {
                    #[allow(non_camel_case_types)]
                    struct GetHoldingsSvc<T: PortfolioService>(pub Arc<T>);
                    impl<
                        T: PortfolioService,
                    > tonic::server::UnaryService<super::HoldingsRequest>
                    for GetHoldingsSvc<T> {
                        type Response = super::HoldingsList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HoldingsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PortfolioService>::get_holdings(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHoldingsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.portfolio.PortfolioService/GetMargins" => {
                    #[allow(non_camel_case_types)]
                    struct GetMarginsSvc<T: PortfolioService>(pub Arc<T>);
                    impl<
                        T: PortfolioService,
                    > tonic::server::ServerStreamingService<super::MarginRequest>
                    for GetMarginsSvc<T> {
                        type Response = super::MarginUpdate;
                        type ResponseStream = T::GetMarginsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MarginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PortfolioService>::get_margins(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMarginsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.portfolio.PortfolioService/GetPnL" => {
                    #[allow(non_camel_case_types)]
                    struct GetPnLSvc<T: PortfolioService>(pub Arc<T>);
                    impl<
                        T: PortfolioService,
                    > tonic::server::ServerStreamingService<super::PnLRequest>
                    for GetPnLSvc<T> {
                        type Response = super::PnLUpdate;
                        type ResponseStream = T::GetPnLStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PnLRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PortfolioService>::get_pn_l(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPnLSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.portfolio.PortfolioService/GetDaySummary" => {
                    #[allow(non_camel_case_types)]
                    struct GetDaySummarySvc<T: PortfolioService>(pub Arc<T>);
                    impl<
                        T: PortfolioService,
                    > tonic::server::UnaryService<super::DaySummaryRequest>
                    for GetDaySummarySvc<T> {
                        type Response = super::DaySummary;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DaySummaryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PortfolioService>::get_day_summary(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetDaySummarySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PortfolioServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nautilus.gateway.portfolio.PortfolioService";
    impl<T> tonic::server::NamedService for PortfolioServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
