// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderSide", tag = "3")]
    pub side: i32,
    #[prost(enumeration = "OrderType", tag = "4")]
    pub order_type: i32,
    #[prost(enumeration = "ProductType", tag = "5")]
    pub product: i32,
    #[prost(int32, tag = "6")]
    pub quantity: i32,
    /// For LIMIT orders
    #[prost(double, tag = "7")]
    pub price: f64,
    /// For SL orders
    #[prost(double, tag = "8")]
    pub trigger_price: f64,
    #[prost(enumeration = "OrderValidity", tag = "9")]
    pub validity: i32,
    #[prost(string, tag = "10")]
    pub broker_id: ::prost::alloc::string::String,
    /// User tag for tracking
    #[prost(string, tag = "11")]
    pub tag: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderStatus", tag = "4")]
    pub status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModifyOrderRequest {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub quantity: i32,
    #[prost(double, tag = "4")]
    pub price: f64,
    #[prost(double, tag = "5")]
    pub trigger_price: f64,
    #[prost(enumeration = "OrderType", tag = "6")]
    pub order_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelOrderRequest {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderFilter {
    #[prost(string, tag = "1")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderStatus", repeated, tag = "2")]
    pub statuses: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, tag = "3")]
    pub from_timestamp: i64,
    #[prost(int64, tag = "4")]
    pub to_timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderUpdate {
    #[prost(string, tag = "1")]
    pub order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderSide", tag = "4")]
    pub side: i32,
    #[prost(enumeration = "OrderType", tag = "5")]
    pub order_type: i32,
    #[prost(enumeration = "ProductType", tag = "6")]
    pub product: i32,
    #[prost(int32, tag = "7")]
    pub quantity: i32,
    #[prost(int32, tag = "8")]
    pub filled_quantity: i32,
    #[prost(double, tag = "9")]
    pub price: f64,
    #[prost(double, tag = "10")]
    pub trigger_price: f64,
    #[prost(double, tag = "11")]
    pub average_price: f64,
    #[prost(enumeration = "OrderStatus", tag = "12")]
    pub status: i32,
    #[prost(string, tag = "13")]
    pub status_message: ::prost::alloc::string::String,
    #[prost(int64, tag = "14")]
    pub timestamp: i64,
    #[prost(string, tag = "15")]
    pub broker_id: ::prost::alloc::string::String,
    #[prost(string, tag = "16")]
    pub tag: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BracketOrderRequest {
    #[prost(message, optional, tag = "1")]
    pub entry: ::core::option::Option<OrderRequest>,
    #[prost(double, tag = "2")]
    pub stoploss: f64,
    #[prost(double, tag = "3")]
    pub target: f64,
    /// In ticks
    #[prost(int32, tag = "4")]
    pub trailing_stoploss: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BracketOrderResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub entry_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stoploss_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub target_order_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GttOrderRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(enumeration = "OrderSide", tag = "3")]
    pub side: i32,
    #[prost(enumeration = "ProductType", tag = "4")]
    pub product: i32,
    #[prost(int32, tag = "5")]
    pub quantity: i32,
    #[prost(double, tag = "6")]
    pub trigger_price: f64,
    #[prost(double, tag = "7")]
    pub limit_price: f64,
    #[prost(enumeration = "GttType", tag = "8")]
    pub gtt_type: i32,
    #[prost(string, tag = "9")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GttOrderResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub gtt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GttCancelRequest {
    #[prost(string, tag = "1")]
    pub gtt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub broker_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderSide {
    Buy = 0,
    Sell = 1,
}
impl OrderSide {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Buy => "ORDER_SIDE_BUY",
            Self::Sell => "ORDER_SIDE_SELL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_SIDE_BUY" => Some(Self::Buy),
            "ORDER_SIDE_SELL" => Some(Self::Sell),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderType {
    Market = 0,
    Limit = 1,
    Sl = 2,
    SlM = 3,
}
impl OrderType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Market => "ORDER_TYPE_MARKET",
            Self::Limit => "ORDER_TYPE_LIMIT",
            Self::Sl => "ORDER_TYPE_SL",
            Self::SlM => "ORDER_TYPE_SL_M",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_TYPE_MARKET" => Some(Self::Market),
            "ORDER_TYPE_LIMIT" => Some(Self::Limit),
            "ORDER_TYPE_SL" => Some(Self::Sl),
            "ORDER_TYPE_SL_M" => Some(Self::SlM),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ProductType {
    /// Intraday
    Mis = 0,
    /// Delivery
    Cnc = 1,
    /// F&O overnight
    Nrml = 2,
}
impl ProductType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Mis => "PRODUCT_TYPE_MIS",
            Self::Cnc => "PRODUCT_TYPE_CNC",
            Self::Nrml => "PRODUCT_TYPE_NRML",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRODUCT_TYPE_MIS" => Some(Self::Mis),
            "PRODUCT_TYPE_CNC" => Some(Self::Cnc),
            "PRODUCT_TYPE_NRML" => Some(Self::Nrml),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderValidity {
    Day = 0,
    Ioc = 1,
    Gtt = 2,
}
impl OrderValidity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Day => "ORDER_VALIDITY_DAY",
            Self::Ioc => "ORDER_VALIDITY_IOC",
            Self::Gtt => "ORDER_VALIDITY_GTT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_VALIDITY_DAY" => Some(Self::Day),
            "ORDER_VALIDITY_IOC" => Some(Self::Ioc),
            "ORDER_VALIDITY_GTT" => Some(Self::Gtt),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OrderStatus {
    Pending = 0,
    Open = 1,
    Complete = 2,
    Cancelled = 3,
    Rejected = 4,
}
impl OrderStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "ORDER_STATUS_PENDING",
            Self::Open => "ORDER_STATUS_OPEN",
            Self::Complete => "ORDER_STATUS_COMPLETE",
            Self::Cancelled => "ORDER_STATUS_CANCELLED",
            Self::Rejected => "ORDER_STATUS_REJECTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ORDER_STATUS_PENDING" => Some(Self::Pending),
            "ORDER_STATUS_OPEN" => Some(Self::Open),
            "ORDER_STATUS_COMPLETE" => Some(Self::Complete),
            "ORDER_STATUS_CANCELLED" => Some(Self::Cancelled),
            "ORDER_STATUS_REJECTED" => Some(Self::Rejected),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GttType {
    Single = 0,
    /// One Cancels Other
    Oco = 1,
}
impl GttType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Single => "GTT_TYPE_SINGLE",
            Self::Oco => "GTT_TYPE_OCO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GTT_TYPE_SINGLE" => Some(Self::Single),
            "GTT_TYPE_OCO" => Some(Self::Oco),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod order_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Order management service
    #[derive(Debug, Clone)]
    pub struct OrderServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OrderServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OrderServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OrderServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            OrderServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Place a new order
        pub async fn place_order(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/PlaceOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("nautilus.gateway.order.OrderService", "PlaceOrder"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Modify an existing order
        pub async fn modify_order(
            &mut self,
            request: impl tonic::IntoRequest<super::ModifyOrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/ModifyOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("nautilus.gateway.order.OrderService", "ModifyOrder"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cancel an order
        pub async fn cancel_order(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelOrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/CancelOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("nautilus.gateway.order.OrderService", "CancelOrder"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream order updates
        pub async fn get_orders(
            &mut self,
            request: impl tonic::IntoRequest<super::OrderFilter>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::OrderUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/GetOrders",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("nautilus.gateway.order.OrderService", "GetOrders"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Place bracket order
        pub async fn place_bracket_order(
            &mut self,
            request: impl tonic::IntoRequest<super::BracketOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BracketOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/PlaceBracketOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.order.OrderService",
                        "PlaceBracketOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Place GTT (Good Till Triggered) order
        pub async fn place_gtt_order(
            &mut self,
            request: impl tonic::IntoRequest<super::GttOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GttOrderResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/PlaceGTTOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.order.OrderService",
                        "PlaceGTTOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Cancel GTT order
        pub async fn cancel_gtt_order(
            &mut self,
            request: impl tonic::IntoRequest<super::GttCancelRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.order.OrderService/CancelGTTOrder",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.order.OrderService",
                        "CancelGTTOrder",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod order_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with OrderServiceServer.
    #[async_trait]
    pub trait OrderService: std::marker::Send + std::marker::Sync + 'static {
        /// Place a new order
        async fn place_order(
            &self,
            request: tonic::Request<super::OrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status>;
        /// Modify an existing order
        async fn modify_order(
            &self,
            request: tonic::Request<super::ModifyOrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status>;
        /// Cancel an order
        async fn cancel_order(
            &self,
            request: tonic::Request<super::CancelOrderRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status>;
        /// Server streaming response type for the GetOrders method.
        type GetOrdersStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::OrderUpdate, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream order updates
        async fn get_orders(
            &self,
            request: tonic::Request<super::OrderFilter>,
        ) -> std::result::Result<tonic::Response<Self::GetOrdersStream>, tonic::Status>;
        /// Place bracket order
        async fn place_bracket_order(
            &self,
            request: tonic::Request<super::BracketOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BracketOrderResponse>,
            tonic::Status,
        >;
        /// Place GTT (Good Till Triggered) order
        async fn place_gtt_order(
            &self,
            request: tonic::Request<super::GttOrderRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GttOrderResponse>,
            tonic::Status,
        >;
        /// Cancel GTT order
        async fn cancel_gtt_order(
            &self,
            request: tonic::Request<super::GttCancelRequest>,
        ) -> std::result::Result<tonic::Response<super::OrderResponse>, tonic::Status>;
    }
    /// Order management service
    #[derive(Debug)]
    pub struct OrderServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> OrderServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for OrderServiceServer<T>
    where
        T: OrderService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nautilus.gateway.order.OrderService/PlaceOrder" => {
                    #[allow(non_camel_case_types)]
                    struct PlaceOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::OrderRequest>
                    for PlaceOrderSvc<T> {
                        type Response = super::OrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::place_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlaceOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/ModifyOrder" => {
                    #[allow(non_camel_case_types)]
                    struct ModifyOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::ModifyOrderRequest>
                    for ModifyOrderSvc<T> {
                        type Response = super::OrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ModifyOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::modify_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ModifyOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/CancelOrder" => {
                    #[allow(non_camel_case_types)]
                    struct CancelOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::CancelOrderRequest>
                    for CancelOrderSvc<T> {
                        type Response = super::OrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CancelOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::cancel_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/GetOrders" => {
                    #[allow(non_camel_case_types)]
                    struct GetOrdersSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::ServerStreamingService<super::OrderFilter>
                    for GetOrdersSvc<T> {
                        type Response = super::OrderUpdate;
                        type ResponseStream = T::GetOrdersStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OrderFilter>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::get_orders(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOrdersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/PlaceBracketOrder" => {
                    #[allow(non_camel_case_types)]
                    struct PlaceBracketOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::BracketOrderRequest>
                    for PlaceBracketOrderSvc<T> {
                        type Response = super::BracketOrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BracketOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::place_bracket_order(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlaceBracketOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/PlaceGTTOrder" => {
                    #[allow(non_camel_case_types)]
                    struct PlaceGTTOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::GttOrderRequest>
                    for PlaceGTTOrderSvc<T> {
                        type Response = super::GttOrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GttOrderRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::place_gtt_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlaceGTTOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.order.OrderService/CancelGTTOrder" => {
                    #[allow(non_camel_case_types)]
                    struct CancelGTTOrderSvc<T: OrderService>(pub Arc<T>);
                    impl<
                        T: OrderService,
                    > tonic::server::UnaryService<super::GttCancelRequest>
                    for CancelGTTOrderSvc<T> {
                        type Response = super::OrderResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GttCancelRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OrderService>::cancel_gtt_order(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CancelGTTOrderSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for OrderServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nautilus.gateway.order.OrderService";
    impl<T> tonic::server::NamedService for OrderServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
