// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstrumentFilter {
    /// Search query (symbol or name)
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// Filter by exchange: NSE, BSE, NFO, etc.
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    /// EQ, FUT, OPT, IDX
    #[prost(string, tag = "3")]
    pub instrument_type: ::prost::alloc::string::String,
    /// Max results to return
    #[prost(int32, tag = "4")]
    pub limit: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instrument {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub instrument_type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub trading_symbol: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub instrument_token: i64,
    #[prost(int32, tag = "7")]
    pub lot_size: i32,
    #[prost(double, tag = "8")]
    pub tick_size: f64,
    /// For derivatives
    #[prost(string, tag = "9")]
    pub expiry: ::prost::alloc::string::String,
    /// For options
    #[prost(double, tag = "10")]
    pub strike: f64,
    /// CE or PE for options
    #[prost(string, tag = "11")]
    pub option_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstrumentList {
    #[prost(message, repeated, tag = "1")]
    pub instruments: ::prost::alloc::vec::Vec<Instrument>,
    #[prost(int32, tag = "2")]
    pub total_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscriptionRequest {
    #[prost(string, repeated, tag = "1")]
    pub symbols: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    #[prost(enumeration = "SubscriptionMode", tag = "3")]
    pub mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarketTick {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    /// Last traded price
    #[prost(double, tag = "3")]
    pub ltp: f64,
    #[prost(double, tag = "4")]
    pub open: f64,
    #[prost(double, tag = "5")]
    pub high: f64,
    #[prost(double, tag = "6")]
    pub low: f64,
    /// Previous close
    #[prost(double, tag = "7")]
    pub close: f64,
    #[prost(int64, tag = "8")]
    pub volume: i64,
    #[prost(double, tag = "9")]
    pub bid: f64,
    #[prost(double, tag = "10")]
    pub ask: f64,
    #[prost(int64, tag = "11")]
    pub bid_qty: i64,
    #[prost(int64, tag = "12")]
    pub ask_qty: i64,
    #[prost(double, tag = "13")]
    pub change: f64,
    #[prost(double, tag = "14")]
    pub change_percent: f64,
    /// Unix timestamp in nanoseconds
    #[prost(int64, tag = "15")]
    pub timestamp: i64,
    /// Open interest (for derivatives)
    #[prost(int64, tag = "16")]
    pub oi: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BarRequest {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub exchange: ::prost::alloc::string::String,
    /// minute, 5minute, 15minute, hour, day
    #[prost(string, tag = "3")]
    pub interval: ::prost::alloc::string::String,
    /// Unix timestamp
    #[prost(int64, tag = "4")]
    pub from_timestamp: i64,
    #[prost(int64, tag = "5")]
    pub to_timestamp: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Bar {
    #[prost(int64, tag = "1")]
    pub timestamp: i64,
    #[prost(double, tag = "2")]
    pub open: f64,
    #[prost(double, tag = "3")]
    pub high: f64,
    #[prost(double, tag = "4")]
    pub low: f64,
    #[prost(double, tag = "5")]
    pub close: f64,
    #[prost(int64, tag = "6")]
    pub volume: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BarList {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub interval: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub bars: ::prost::alloc::vec::Vec<Bar>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionChainRequest {
    /// e.g., "NIFTY", "BANKNIFTY"
    #[prost(string, tag = "1")]
    pub underlying: ::prost::alloc::string::String,
    /// YYYY-MM-DD format
    #[prost(string, tag = "2")]
    pub expiry: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionChain {
    #[prost(string, tag = "1")]
    pub underlying: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub expiry: ::prost::alloc::string::String,
    #[prost(double, tag = "3")]
    pub spot_price: f64,
    #[prost(message, repeated, tag = "4")]
    pub strikes: ::prost::alloc::vec::Vec<OptionStrike>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionStrike {
    #[prost(double, tag = "1")]
    pub strike_price: f64,
    #[prost(message, optional, tag = "2")]
    pub call: ::core::option::Option<OptionData>,
    #[prost(message, optional, tag = "3")]
    pub put: ::core::option::Option<OptionData>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionData {
    #[prost(string, tag = "1")]
    pub symbol: ::prost::alloc::string::String,
    #[prost(double, tag = "2")]
    pub ltp: f64,
    #[prost(double, tag = "3")]
    pub bid: f64,
    #[prost(double, tag = "4")]
    pub ask: f64,
    #[prost(int64, tag = "5")]
    pub volume: i64,
    #[prost(int64, tag = "6")]
    pub oi: i64,
    /// Implied volatility
    #[prost(double, tag = "7")]
    pub iv: f64,
    #[prost(double, tag = "8")]
    pub delta: f64,
    #[prost(double, tag = "9")]
    pub gamma: f64,
    #[prost(double, tag = "10")]
    pub theta: f64,
    #[prost(double, tag = "11")]
    pub vega: f64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SubscriptionMode {
    Ltp = 0,
    Quote = 1,
    Full = 2,
}
impl SubscriptionMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ltp => "SUBSCRIPTION_MODE_LTP",
            Self::Quote => "SUBSCRIPTION_MODE_QUOTE",
            Self::Full => "SUBSCRIPTION_MODE_FULL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUBSCRIPTION_MODE_LTP" => Some(Self::Ltp),
            "SUBSCRIPTION_MODE_QUOTE" => Some(Self::Quote),
            "SUBSCRIPTION_MODE_FULL" => Some(Self::Full),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod market_data_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Market data service for quotes, charts, and instruments
    #[derive(Debug, Clone)]
    pub struct MarketDataServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MarketDataServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MarketDataServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MarketDataServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MarketDataServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Search and list instruments
        pub async fn get_instruments(
            &mut self,
            request: impl tonic::IntoRequest<super::InstrumentFilter>,
        ) -> std::result::Result<tonic::Response<super::InstrumentList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.market_data.MarketDataService/GetInstruments",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.market_data.MarketDataService",
                        "GetInstruments",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to live market data
        pub async fn subscribe(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscriptionRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MarketTick>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.market_data.MarketDataService/Subscribe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.market_data.MarketDataService",
                        "Subscribe",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get historical bars/candles
        pub async fn get_historical_bars(
            &mut self,
            request: impl tonic::IntoRequest<super::BarRequest>,
        ) -> std::result::Result<tonic::Response<super::BarList>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.market_data.MarketDataService/GetHistoricalBars",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.market_data.MarketDataService",
                        "GetHistoricalBars",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get option chain for an underlying
        pub async fn get_option_chain(
            &mut self,
            request: impl tonic::IntoRequest<super::OptionChainRequest>,
        ) -> std::result::Result<tonic::Response<super::OptionChain>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/nautilus.gateway.market_data.MarketDataService/GetOptionChain",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "nautilus.gateway.market_data.MarketDataService",
                        "GetOptionChain",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod market_data_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MarketDataServiceServer.
    #[async_trait]
    pub trait MarketDataService: std::marker::Send + std::marker::Sync + 'static {
        /// Search and list instruments
        async fn get_instruments(
            &self,
            request: tonic::Request<super::InstrumentFilter>,
        ) -> std::result::Result<tonic::Response<super::InstrumentList>, tonic::Status>;
        /// Server streaming response type for the Subscribe method.
        type SubscribeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::MarketTick, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Subscribe to live market data
        async fn subscribe(
            &self,
            request: tonic::Request<super::SubscriptionRequest>,
        ) -> std::result::Result<tonic::Response<Self::SubscribeStream>, tonic::Status>;
        /// Get historical bars/candles
        async fn get_historical_bars(
            &self,
            request: tonic::Request<super::BarRequest>,
        ) -> std::result::Result<tonic::Response<super::BarList>, tonic::Status>;
        /// Get option chain for an underlying
        async fn get_option_chain(
            &self,
            request: tonic::Request<super::OptionChainRequest>,
        ) -> std::result::Result<tonic::Response<super::OptionChain>, tonic::Status>;
    }
    /// Market data service for quotes, charts, and instruments
    #[derive(Debug)]
    pub struct MarketDataServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MarketDataServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MarketDataServiceServer<T>
    where
        T: MarketDataService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/nautilus.gateway.market_data.MarketDataService/GetInstruments" => {
                    #[allow(non_camel_case_types)]
                    struct GetInstrumentsSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::InstrumentFilter>
                    for GetInstrumentsSvc<T> {
                        type Response = super::InstrumentList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::InstrumentFilter>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_instruments(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetInstrumentsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.market_data.MarketDataService/Subscribe" => {
                    #[allow(non_camel_case_types)]
                    struct SubscribeSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::ServerStreamingService<super::SubscriptionRequest>
                    for SubscribeSvc<T> {
                        type Response = super::MarketTick;
                        type ResponseStream = T::SubscribeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SubscriptionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::subscribe(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SubscribeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.market_data.MarketDataService/GetHistoricalBars" => {
                    #[allow(non_camel_case_types)]
                    struct GetHistoricalBarsSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::BarRequest>
                    for GetHistoricalBarsSvc<T> {
                        type Response = super::BarList;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BarRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_historical_bars(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHistoricalBarsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/nautilus.gateway.market_data.MarketDataService/GetOptionChain" => {
                    #[allow(non_camel_case_types)]
                    struct GetOptionChainSvc<T: MarketDataService>(pub Arc<T>);
                    impl<
                        T: MarketDataService,
                    > tonic::server::UnaryService<super::OptionChainRequest>
                    for GetOptionChainSvc<T> {
                        type Response = super::OptionChain;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::OptionChainRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MarketDataService>::get_option_chain(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetOptionChainSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MarketDataServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "nautilus.gateway.market_data.MarketDataService";
    impl<T> tonic::server::NamedService for MarketDataServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
